
#ifndef WEATHER_ICONS_H
#define WEATHER_ICONS_H
///File auto generated by script.py

#include "blue_cloud_and_weather.c"
#include "blue_clouds_and_blue_moon.c"
#include "blue_clouds_and_yellow_sun.c"
#include "blue_moon_and_snowy_night.c"
#include "blue_thermometer_and_cold.c"
#include "blue_thermometer_and_heat.c"
#include "cloud_and_yellow_lightning.c"
#include "downpour_rainy_day.c"
#include "hail_weather_and_winter_cloud.c"
#include "lightning_and_blue_rain_cloud.c"
#include "moon_and_cloudy_night.c"
#include "rain_and_blue_cloud.c"
#include "rainy_and_cloudy_day.c"
#include "rainy_night_and_clouds_with_moon.c"
#include "snow_and_blue_cloud.c"
#include "snowfall_and_blue_cloud.c"
#include "yellow_moon.c"
#include "yellow_sun.c"
#include "yellow_sun_and_blue_cloud.c"
#include "yellow_sun_and_blue_rain_cloud.c"
#include "yellow_sun_and_snow_with_blue_cloud.c"

LV_IMG_DECLARE(w_blue_cloud_and_weather_16527)
LV_IMG_DECLARE(w_blue_clouds_and_blue_moon_16538)
LV_IMG_DECLARE(w_blue_clouds_and_yellow_sun_16529)
LV_IMG_DECLARE(w_blue_moon_and_snowy_night_16543)
LV_IMG_DECLARE(w_blue_thermometer_and_cold_16548)
LV_IMG_DECLARE(w_blue_thermometer_and_heat_16549)
LV_IMG_DECLARE(w_cloud_and_yellow_lightning_16534)
LV_IMG_DECLARE(w_downpour_rainy_day_16531)
LV_IMG_DECLARE(w_hail_weather_and_winter_cloud_16559)
LV_IMG_DECLARE(w_lightning_and_blue_rain_cloud_16533)
LV_IMG_DECLARE(w_moon_and_cloudy_night_16537)
LV_IMG_DECLARE(w_rain_and_blue_cloud_16530)
LV_IMG_DECLARE(w_rainy_and_cloudy_day_16532)
LV_IMG_DECLARE(w_rainy_night_and_clouds_with_moon_16539)
LV_IMG_DECLARE(w_snow_and_blue_cloud_16540)
LV_IMG_DECLARE(w_snowfall_and_blue_cloud_16541)
LV_IMG_DECLARE(w_yellow_moon_16536)
LV_IMG_DECLARE(w_yellow_sun_16526)
LV_IMG_DECLARE(w_yellow_sun_and_blue_cloud_16528)
LV_IMG_DECLARE(w_yellow_sun_and_blue_rain_cloud_16535)
LV_IMG_DECLARE(w_yellow_sun_and_snow_with_blue_cloud_16542)

#define WEATHER_ICONS_SIZE 21

///@brief Gets a weather icon based on the img ID
///@param img_id The index of the icon
///@return a const lv_img_dsc_t* to the icon
            const lv_img_dsc_t* get_weather_icons(uint8_t img_id)
{
	if (img_id == 0)
		return &w_blue_cloud_and_weather_16527;
	else if (img_id == 1)
		return &w_blue_clouds_and_blue_moon_16538;
	else if (img_id == 2)
		return &w_blue_clouds_and_yellow_sun_16529;
	else if (img_id == 3)
		return &w_blue_moon_and_snowy_night_16543;
	else if (img_id == 4)
		return &w_blue_thermometer_and_cold_16548;
	else if (img_id == 5)
		return &w_blue_thermometer_and_heat_16549;
	else if (img_id == 6)
		return &w_cloud_and_yellow_lightning_16534;
	else if (img_id == 7)
		return &w_downpour_rainy_day_16531;
	else if (img_id == 8)
		return &w_hail_weather_and_winter_cloud_16559;
	else if (img_id == 9)
		return &w_lightning_and_blue_rain_cloud_16533;
	else if (img_id == 10)
		return &w_moon_and_cloudy_night_16537;
	else if (img_id == 11)
		return &w_rain_and_blue_cloud_16530;
	else if (img_id == 12)
		return &w_rainy_and_cloudy_day_16532;
	else if (img_id == 13)
		return &w_rainy_night_and_clouds_with_moon_16539;
	else if (img_id == 14)
		return &w_snow_and_blue_cloud_16540;
	else if (img_id == 15)
		return &w_snowfall_and_blue_cloud_16541;
	else if (img_id == 16)
		return &w_yellow_moon_16536;
	else if (img_id == 17)
		return &w_yellow_sun_16526;
	else if (img_id == 18)
		return &w_yellow_sun_and_blue_cloud_16528;
	else if (img_id == 19)
		return &w_yellow_sun_and_blue_rain_cloud_16535;
	else if (img_id == 20)
		return &w_yellow_sun_and_snow_with_blue_cloud_16542;
	return NULL;
}

#endif