/*----------------------------------------------------------
 * NightMareConfig.h -- feature selection for the NightMare Network library.
 *
 * Replaces the old Modules.config.h. The library's NightMare/Features.h picks
 * this file up automatically (__has_include <NightMareConfig.h>) and supplies a
 * default for anything left out, so only the choices that differ from the
 * library's defaults need to be here -- but the whole set is listed, because
 * one explicit place to read the panel's feature choices is worth the lines.
 *----------------------------------------------------------*/

#pragma once

// VERSION / BUILD_TIMESTAMP, generated by src/Version/script.py before the
// build. Included here rather than left to main.cpp so the library's own
// intro banner and the BUILD section of <device>/info carry them too.
#include <Version.h>

#ifdef VERSION
#define NM_FIRMWARE_VERSION VERSION
#endif

#pragma region "Services"

#define NM_ENABLE_SETTINGS 1
#define NM_ENABLE_RESOURCES 1
#define NM_ENABLE_NETWORK 1
#define NM_ENABLE_CONSOLE 1
#define NM_ENABLE_WIFI 1
#define NM_ENABLE_MQTT 1
#define NM_ENABLE_TELEMETRY 1
#define NM_ENABLE_SCHEDULER 1
#define NM_ENABLE_JOBS 1
#define NM_ENABLE_TIME_SYNC 1

// The panel reads the console over USB; it is the only way in without a broker.
#define NM_CONSOLE_SERIAL 1
#define NM_CONSOLE_BUILTINS 1

// OTA, on src/OtaDual.csv's two 0x1F0000 slots. The firmware was cut to fit
// them: 160,944 bytes of image data came out of it, leaving 25,077 bytes of
// slot free with OTA compiled in -- 1.2%. That is the flash budget from here
// on, and it does not grow.
//
// The flash was never the hard part. ArduinoOTA holds a 4KB task stack, an mDNS
// responder and a UDP listener from boot to power-off, out of the same heap the
// TLS handshake cannot currently find 32KB of contiguous space in. This panel
// reaches 244 bytes free once it has joined the network; OTA makes that worse
// permanently, not only while an update is running.
//
// Tried on hardware, 2026-09-23, and turned back off. It was the difference
// between a panel that connects and one that does not:
//
//                        free at [net] start   outcome
//   NM_ENABLE_OTA 0            135,008         reaches 'mqtt up', free=5,040
//   NM_ENABLE_OTA 1            132,612         never connects
//
// With it on the handshake drives the heap to largest=388 and fails with
// mbedtls_ssl_handshake -0x2880, which is MBEDTLS_ERR_X509_ALLOC_FAILED --
// mbedTLS naming the out-of-memory outright rather than reporting it as the
// -0x2700 cert-verify failure it used to. ~2.4KB of static RAM plus the OTA
// task's 4KB stack, mDNS and the UDP listener was the whole margin.
//
// The flash work stands: src/OtaDual.csv's two 0x1F0000 slots are in place and
// the firmware fits them with 55,284 bytes spare. This is the only line that
// needs changing once the panel has heap to spare -- which means fixing the
// TLS record buffers, since nothing else on this board is worth 32KB.
#define NM_ENABLE_OTA 0
// Nothing serves pages from the wall, and both cost heap and a task.
#define NM_ENABLE_HTTP 0
#define NM_ENABLE_WEBSOCKET 0
// The panel drives LVGL itself (lib/lvgl + lib/boardstuff), so the library's own
// LVGL helpers would be a second, conflicting owner of the display.
#define NM_ENABLE_LVGL 0

#pragma endregion

#pragma region "Threading"

// LOAD-BEARING. With this at 1 the Scheduler gets its own FreeRTOS task, and
// every job callback -- the forecast refresh, the heap log -- would run in
// parallel with loop(). Everything those callbacks touch (the forecast model,
// the registry's Strings, LVGL) is also read by loop() to draw the screen, and
// two tasks reallocating the same String corrupts the heap.
//
// At 0 nothing runs jobs but tickNightMareESP(), which loop() calls, so the
// panel keeps its single-task invariant: application state is touched by the
// loop() task and nothing else. See the threading note at the top of App/Net.cpp
// for the other half of the same rule, which covers MQTT ingress.
#define NM_SCHEDULER_OWN_TASK 0

#pragma endregion

#pragma region "Time"

// POSIX TZ for UTC-3 with no daylight saving, which is what `#define GMT -3` in
// creds.h used to mean. introNightMareESP() prefers the `ac_timezone` setting
// when one is stored, so a panel can be moved without a reflash.
#define NM_TIMEZONE "<-03>3"

#define NM_NTP_SERVER_1 "pool.ntp.org"
#define NM_NTP_SERVER_2 "time.nist.gov"
#define NM_NTP_SERVER_3 "time.google.com"

#pragma endregion

#pragma region "Bookkeeping"

#define NM_TELEMETRY_INTERVAL_MS 60000UL
#define NM_NETWORK_TELEMETRY_INTERVAL_MS 300000UL
#define NM_IDENTITY_CLEANUP_RETRY_MS 60000UL

// The panel implements no action of its own, so there is no payload to assert.
#define NM_ENABLE_ACTION_PAYLOAD_ASSERTION 0

// NM_LOG_LEVEL_WARNING. Serial is a console someone is reading at the wall, so
// the library's INFO chatter would bury the panel's own lines.
#define NM_LOG_LEVEL 2

#pragma endregion
